import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { createPublicClient, http, keccak256, toHex } from "viem";
import { base as viemBase } from "viem/chains";
import { AcpAgent, AssetToken, PrivyAlchemyEvmProviderAdapter } from "@virtuals-protocol/acp-node-v2";
import { base } from "@account-kit/infra";

// Buyer / evaluator side of the ACP adjudication lifecycle.
//
// Hardening notes (learned the hard way on Base Mainnet jobs 77935-78154):
//  * JobSession has no `deliverable` property; the body must be read from the
//    `job.submitted` entry or from AcpJob.deliverable via session.fetchJob().
//  * A missing body is NOT a malformed deliverable. Rejecting on an unresolved
//    body burns the job; this runner reports and exits instead.
//  * waitForCallsStatus() resolves as soon as a receipt exists, so a reverted
//    complete() still looks successful. The proof is only written after the
//    on-chain job status is independently read back as COMPLETED.
//  * Two runners polling the same agent can race (one completes, one rejects).
//    This runner pins itself to a single job with --job and always exits.

const ACP_MAINNET = "0x238E541BfefD82238730D00a2208E5497F1832E0" as const;
const JOB_STATUS = ["OPEN", "FUNDED", "SUBMITTED", "COMPLETED", "REJECTED", "EXPIRED"];
const REQUIRED_FIELDS = ["decision", "winning_claim", "reason_code", "evidence_digest", "adjudicated_at"];
const COMPLETED = 3;
const GET_JOB_ABI = [
  {
    inputs: [{ internalType: "uint256", name: "jobId", type: "uint256" }],
    name: "getJob",
    outputs: [
      {
        components: [
          { internalType: "address", name: "client", type: "address" },
          { internalType: "uint8", name: "status", type: "uint8" },
          { internalType: "address", name: "provider", type: "address" },
          { internalType: "uint48", name: "expiredAt", type: "uint48" },
          { internalType: "address", name: "evaluator", type: "address" },
          { internalType: "address", name: "hook", type: "address" },
          { internalType: "uint256", name: "budget", type: "uint256" },
          { internalType: "string", name: "description", type: "string" },
        ],
        internalType: "struct AgenticCommerceV3.Job",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const flag = (name: string): string | null => {
  const i = process.argv.indexOf(name);
  return i === -1 ? null : (process.argv[i + 1] ?? null);
};
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const log = (payload: Record<string, unknown>) => console.log(JSON.stringify({ at: new Date().toISOString(), ...payload }));
const sha256 = (value: string) => "sha256:" + createHash("sha256").update(value, "utf8").digest("hex");
const digest = (value: unknown) => createHash("sha256").update(JSON.stringify(value)).digest("hex");

const required = ["ACP_BUYER_WALLET_ADDRESS", "ACP_BUYER_WALLET_ID", "ACP_BUYER_SIGNER_PRIVATE_KEY", "ACP_PROVIDER_WALLET_ADDRESS", "ACP_OFFERING_NAME"] as const;
const missingVars = required.filter((key) => !process.env[key] || process.env[key]!.startsWith("replace_"));
const buyerSigner = process.env.ACP_BUYER_SIGNER_PRIVATE_KEY ?? "";
const signerError = /^0x?[0-9a-f]{64}$/i.test(buyerSigner)
  ? "ACP_BUYER_SIGNER_PRIVATE_KEY is a raw 32-byte hex key; v2 requires the Privy wallet-authorization signer generated by the ACP Signers flow (PKCS#8 PEM)."
  : null;
if (process.argv.includes("--check")) {
  if (missingVars.length) { console.error(`Missing ACP registry credentials: ${missingVars.join(", ")}`); process.exit(2); }
  if (signerError) { console.error(signerError); process.exit(3); }
  console.log(`ACP v2 credentials configured; buyer=${process.env.ACP_BUYER_WALLET_ADDRESS} provider=${process.env.ACP_PROVIDER_WALLET_ADDRESS} offering=${process.env.ACP_OFFERING_NAME}`);
  process.exit(0);
}
if (missingVars.length) throw new Error(`Missing ACP registry credentials: ${missingVars.join(", ")}`);
if (signerError) throw new Error(signerError);

const requirementPath = "proof/acp_requirement.json";
if (!existsSync(requirementPath)) {
  throw new Error(`${requirementPath} not found - generate the real contested state with experiments/acp_requirement.py first (no synthetic ACP evidence is permitted).`);
}
const contested = JSON.parse(readFileSync(requirementPath, "utf8"));
const inputDigest = digest(contested);

const budgetUsdc = Number(flag("--budget") ?? process.env.ACP_BUDGET_USDC ?? "0.01");
const pinnedJobId = flag("--job") ?? process.env.ACP_JOB_ID ?? null;
const fetchAttempts = Number(flag("--fetch-attempts") ?? "20");
const fetchDelayMs = Number(flag("--fetch-delay-ms") ?? "3000");
const confirmAttempts = Number(flag("--confirm-attempts") ?? "24");
const confirmDelayMs = Number(flag("--confirm-delay-ms") ?? "5000");
const timeoutMinutes = Number(flag("--timeout-minutes") ?? "30");
const rpcUrl = process.env.BASE_RPC_URL ?? "https://mainnet.base.org";
const chain = createPublicClient({ chain: viemBase, transport: http(rpcUrl, { timeout: 20000, retryCount: 2 }) });

let settled = false;
let buyer: Awaited<ReturnType<typeof AcpAgent.create>> | null = null;

async function onchainJob(jobId: string) {
  const job = await chain.readContract({ address: ACP_MAINNET, abi: GET_JOB_ABI, functionName: "getJob", args: [BigInt(jobId)] });
  const code = Number(job.status);
  return { status_code: code, status: JOB_STATUS[code] ?? "UNKNOWN(" + code + ")" };
}

async function writeEvidence(fileName: string, payload: Record<string, unknown>) {
  await mkdir("proof", { recursive: true });
  await writeFile(`proof/${fileName}`, JSON.stringify(payload, null, 2) + "\n");
}

async function finish(code: number) {
  if (settled) return;
  settled = true;
  try { if (buyer) await (buyer as any).stop(); } catch {}
  process.exit(code);
}

async function resolveDeliverable(session: any, initial: unknown): Promise<string> {
  const found: string[] = [];
  const remember = (value: unknown) => { if (typeof value === "string" && value.trim()) found.push(value); };
  remember(initial);
  for (let attempt = 1; attempt <= fetchAttempts && found.length === 0; attempt++) {
    try {
      const job = (await session.fetchJob()) as { deliverable?: unknown } | null;
      remember(job?.deliverable);
    } catch (err) {
      log({ event: "deliverable.fetch-error", attempt, error: String(err) });
    }
    if (found.length === 0) await sleep(fetchDelayMs);
  }
  return found[0] ?? "";
}

buyer = await AcpAgent.create({
  evmProvider: await PrivyAlchemyEvmProviderAdapter.create({
    walletAddress: process.env.ACP_BUYER_WALLET_ADDRESS!,
    walletId: process.env.ACP_BUYER_WALLET_ID!,
    signerPrivateKey: buyerSigner,
    chains: [base],
  }),
});

buyer.on("entry", async (session: any, entry: any) => {
  try {
    if (entry.kind !== "system") return;
    const jobId = String(session.jobId);
    if (pinnedJobId && jobId !== pinnedJobId) return;
    const event = entry.event.type as string;
    log({ event, jobId, status: session.status });

    if (event === "budget.set") {
      log({ event: "funding", jobId, amount_usdc: budgetUsdc });
      await session.fund(AssetToken.usdc(budgetUsdc, session.chainId));
      return;
    }

    if (event === "job.submitted" && !settled) {
      const raw = await resolveDeliverable(session, entry.event.deliverable);
      const observed = { jobId, bytes: Buffer.byteLength(raw, "utf8"), sha256: raw ? sha256(raw) : null, keccak256: raw ? keccak256(toHex(raw)) : null };
      log({ event: "deliverable.resolved", ...observed });
      if (!raw) {
        await writeEvidence("acp_arbitration_failure.json", {
          observed_at: new Date().toISOString(), acp_job_id: jobId, chain_id: base.id,
          buyer_agent: process.env.ACP_BUYER_WALLET_ADDRESS, provider_agent: process.env.ACP_PROVIDER_WALLET_ADDRESS,
          provider_offering: process.env.ACP_OFFERING_NAME, phase: "deliverable-missing",
          fetch_attempts: fetchAttempts, note: "No deliverable body was retrievable. Not rejecting: an unreadable body is a transport/indexing failure, not a malformed deliverable.",
        });
        log({ event: "arbitration.not-persisted", jobId, reason: "deliverable-missing" });
        await finish(4);
        return;
      }
      let deliverable: Record<string, unknown>;
      try { deliverable = JSON.parse(raw); }
      catch {
        await session.reject("malformed-deliverable");
        await writeEvidence("acp_arbitration_failure.json", {
          observed_at: new Date().toISOString(), acp_job_id: jobId, phase: "invalid-json",
          deliverable_digest: observed.sha256, deliverable_keccak256: observed.keccak256, deliverable_bytes: observed.bytes,
        });
        log({ event: "arbitration.not-persisted", jobId, reason: "invalid-json" });
        await finish(5);
        return;
      }
      const badFields = REQUIRED_FIELDS.filter((field) => typeof deliverable[field] !== "string");
      if (badFields.length) {
        await session.reject("invalid-schema");
        await writeEvidence("acp_arbitration_failure.json", {
          observed_at: new Date().toISOString(), acp_job_id: jobId, phase: "invalid-schema",
          missing_or_non_string_fields: badFields, deliverable,
        });
        log({ event: "arbitration.not-persisted", jobId, reason: "invalid-schema", badFields });
        await finish(6);
        return;
      }

      log({ event: "deliverable.validated", jobId, deliverable });
      await session.complete("Structured adjudication accepted");

      let confirmation: { status_code: number; status: string } | null = null;
      for (let attempt = 1; attempt <= confirmAttempts; attempt++) {
        try { confirmation = await onchainJob(jobId); } catch (err) { log({ event: "confirmation.read-error", attempt, error: String(err) }); }
        if (confirmation && confirmation.status_code === COMPLETED) break;
        if (confirmation && (confirmation.status === "REJECTED" || confirmation.status === "EXPIRED")) break;
        await sleep(confirmDelayMs);
      }
      log({ event: "completion.checked", jobId, confirmation });

      if (!confirmation || confirmation.status_code !== COMPLETED) {
        await writeEvidence("acp_arbitration_failure.json", {
          observed_at: new Date().toISOString(), acp_job_id: jobId, chain_id: base.id,
          buyer_agent: process.env.ACP_BUYER_WALLET_ADDRESS, provider_agent: process.env.ACP_PROVIDER_WALLET_ADDRESS,
          provider_offering: process.env.ACP_OFFERING_NAME, phase: "completion-not-confirmed",
          observed_onchain_status: confirmation, deliverable, deliverable_digest: observed.sha256,
          deliverable_keccak256: observed.keccak256,
          note: "complete() was submitted but the on-chain job status never read back as COMPLETED, so no arbitration proof was written.",
        });
        log({ event: "arbitration.not-persisted", jobId, reason: "completion-not-confirmed", observed: confirmation });
        await finish(7);
        return;
      }

      await writeEvidence("acp_arbitration.json", {
        acp_job_id: jobId, chain_id: base.id, network: "base-mainnet", acp_contract: ACP_MAINNET,
        buyer_agent: process.env.ACP_BUYER_WALLET_ADDRESS, provider_agent: process.env.ACP_PROVIDER_WALLET_ADDRESS,
        provider_offering: process.env.ACP_OFFERING_NAME,
        requirement: contested, input_digest: inputDigest,
        deliverable, deliverable_digest: observed.sha256, deliverable_keccak256: observed.keccak256,
        deliverable_bytes: observed.bytes,
        completion: { verified_onchain_status: confirmation.status, status_code: confirmation.status_code, verified_at: new Date().toISOString() },
        received_at: new Date().toISOString(),
      });
      log({ event: "arbitration.persisted", jobId, status: confirmation.status, deliverable_digest: observed.sha256 });
      await finish(0);
      return;
    }

    if (event === "job.completed") {
      log({ event: "job.completed", jobId, note: "run scripts/acp_inspect.ts for the verified event history" });
      return;
    }

    if (event === "job.rejected" || event === "job.expired") {
      await writeEvidence("acp_arbitration_failure.json", {
        observed_at: new Date().toISOString(), acp_job_id: jobId, chain_id: base.id,
        buyer_agent: process.env.ACP_BUYER_WALLET_ADDRESS, provider_agent: process.env.ACP_PROVIDER_WALLET_ADDRESS,
        provider_offering: process.env.ACP_OFFERING_NAME, phase: event, reason: entry.event.reason ?? null,
      });
      log({ event: "arbitration.not-persisted", jobId, reason: event });
      await finish(8);
    }
  } catch (err) {
    log({ event: "runner.error", error: String(err), stack: (err as Error)?.stack ?? null });
  }
});

await buyer.start(() => log({ connected: true, chain_id: base.id, buyer: process.env.ACP_BUYER_WALLET_ADDRESS, pinned_job: pinnedJobId }));
const buyerAddress = await buyer.getAddress();

if (pinnedJobId) {
  const session = (buyer as any).getSession(base.id, BigInt(pinnedJobId));
  if (!session) throw new Error(`ACP job ${pinnedJobId} was not found in the persisted buyer sessions`);
  log({ event: "attached", jobId: pinnedJobId, status: session.status });
  if (session.status === "budget_set") {
    log({ event: "funding", jobId: pinnedJobId, amount_usdc: budgetUsdc, note: "job was already budget_set on attach" });
    await session.fund(AssetToken.usdc(budgetUsdc, base.id));
  }
} else {
  const jobId = await buyer.createJobByOfferingName(base.id, process.env.ACP_OFFERING_NAME!, process.env.ACP_PROVIDER_WALLET_ADDRESS!, contested, { evaluatorAddress: buyerAddress });
  await mkdir(".runs", { recursive: true });
  await writeFile(".runs/acp_active_job.json", JSON.stringify({ acp_job_id: jobId.toString(), created_at: new Date().toISOString(), buyer_agent: buyerAddress, provider_agent: process.env.ACP_PROVIDER_WALLET_ADDRESS, provider_offering: process.env.ACP_OFFERING_NAME, budget_usdc: budgetUsdc }, null, 2) + "\n");
  log({ event: "job.created", jobId: jobId.toString(), buyer: buyerAddress, provider: process.env.ACP_PROVIDER_WALLET_ADDRESS, offering: process.env.ACP_OFFERING_NAME, requirement: contested });
}

setTimeout(() => {
  if (!settled) {
    log({ event: "runner.timeout", timeout_minutes: timeoutMinutes });
    finish(9);
  }
}, timeoutMinutes * 60_000);
